# Generated by Django 5.2.17 on 2026-10-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('GENERAL', 'General Information'), ('DEPARTMENTS', 'Departments & Courses'), ('FACULTY', 'Faculty & HODs'), ('ADMISSIONS', 'Admissions & Eligibility'), ('FEES', 'Fees & Scholarships'), ('EXAMS', 'Examinations & Results'), ('CALENDAR', 'Academic Calendar & Dates'), ('TIMINGS', 'College Timings'), ('CONTACTS', 'Contact & Office Hours'), ('RULES', 'Rules & Regulations'), ('FACILITIES', 'Campus Facilities & Labs'), ('HOSTEL', 'Hostel & Mess'), ('EVENTS', 'Events & Activities'), ('PLACEMENTS', 'Placements & Careers'), ('FAQ', 'Frequently Asked Questions')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Knowledge Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('keywords', models.CharField(blank=True, default='', help_text='Comma-separated search phrases', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='ai_assistant.knowledgecategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-priority', 'question'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='knowledge_docs/')),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
                ('extracted_text', models.TextField(blank=True, default='', help_text='Text automatically parsed from document')),
                ('is_indexed', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ai_assistant.knowledgecategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Detailed information, facts, lists, or instructions.')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated keywords e.g. mca, hod, subjects', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority items are ranked first in search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_assistant.knowledgecategory')),
            ],
            options={
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentInquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25)),
                ('question', models.TextField()),
                ('detected_intent', models.CharField(blank=True, default='', max_length=150)),
                ('retrieved_context', models.TextField(blank=True, default='')),
                ('answer', models.TextField()),
                ('status', models.CharField(choices=[('ANSWERED', 'Answered'), ('FALLBACK', 'Fallback (No Info)'), ('ERROR', 'Error')], default='ANSWERED', max_length=20)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SIMULATOR', 'Web Simulator')], default='WHATSAPP', max_length=20)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_inquiries', to='contacts.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
