# Generated by Django 5.2.7 on 2026-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(help_text='With country code e.g. 919876543210', max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('HOD', 'Head of Department'), ('PARENT', 'Parent'), ('OTHER', 'Other')], default='STUDENT', max_length=10)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('year_or_section', models.CharField(blank=True, default='', max_length=50)),
                ('enrollment_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('group_type', models.CharField(choices=[('ROLE', 'Role-based'), ('DEPARTMENT', 'Department-based'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='contacts.contact')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
