# Generated by Django 5.2.7 on 2026-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name', max_length=200)),
                ('meta_template_name', models.CharField(help_text='Name registered with Meta', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('UTILITY', 'Utility'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('header_text', models.CharField(blank=True, default='', max_length=500)),
                ('body_text', models.TextField(help_text='Template body. Use {{1}}, {{2}} etc for variables')),
                ('footer_text', models.CharField(blank=True, default='', max_length=200)),
                ('param_count', models.IntegerField(default=0, help_text='Number of {{N}} placeholders in body')),
                ('sample_params', models.JSONField(blank=True, default=list, help_text='Sample values for parameters')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
